### PR TITLE
Upgrade dependencies + make crates inherit workspace deps

### PR DESCRIPTION
**Pull request by friendlymatthew**

### CODE REVIEW

**Comment by mondeja** [comment]
You need to run `cargo update`.

**Comment by friendlymatthew** [comment]
> Hi @friendlymatthew. I think that you need to run `cargo update`.

Thanks. Removed `leptos_theme` since that project is no longer alive.

Have you used `just`? https://github.com/casey/just

It's super nice and so far I've been really enjoying it.

**Comment by mondeja** [comment]
> > Hi @friendlymatthew. I think that you need to run `cargo update`.
> 
> Thanks. Removed `leptos_theme` since that project is no longer alive.
> 
> Have you used `just`? https://github.com/casey/just
> 
> It's super nice and so far I've been really enjoying it.

Yep, it's nice but never faced a big project with it. I've preferred `cargo-make` because it was duckscript builtin and that allows to write crossplatform scripts, to make the build pipelines work on Windows as well. Does `just` have such a thing?

For theming I would recommend leptos-use's `[use-color-mode](https://leptos-use.rs/browser/use_color_mode.html)` and/or `[use-preferred-dark](https://leptos-use.rs/browser/use_preferred_dark.html)`.

**Review by mondeja — APPROVED** [review]

**Comment by friendlymatthew** [comment]
> I've preferred `cargo-make` because it was duckscript builtin and that allows to write crossplatform scripts, to make the build pipelines work on Windows as well. Does `just` have such a thing?

I'm not sure. FWIW just is just a command runner. I use it at work and so far I just like how simple it is. Very readable as well!

**Pull request merged**
