### PR TITLE
feat: change to ev::keydown

### LINKED ISSUE #91: Inconsistent results across browsers for use_hotkeys_ref
Hi, thanks for putting time into this awesome library!

I'm having trouble using the hotkeys_ref. The Callback doesn't seem to fire on Firefox 125.0b3 but it works as expected in Edge 123.0.2420.65. Same behavior on the demo site. 

I am by no means an expert, but looking at the source code, I noticed that is is adding an event listener for keypress, rather than keydown. Since that event type is deprecated, maybe that has something to do with it? Other than that, I'm not sure what could account for the inconsistent behavior.

### PR DESCRIPTION
**Pull request by friendlymatthew**
Fixes #91 

Context: https://docs.rs/leptos/latest/leptos/ev/struct.keydown.html

### CODE REVIEW

**Review by mondeja — APPROVED** [review]
Should be fine 👍🏼

**Review by mondeja — COMMENTED** [review]
Would you mind to add a changelog entry within a header `### Fixes`?

**Comment by friendlymatthew** [comment]
> Would you mind to add a changelog entry within a header `### Fixes`?

Yes of course. Will do this tomorrow first thing

**Comment by mondeja** [comment]
If you resolve #80 we can release the final v0.2.0

**Pull request merged**
