### PR TITLE
Determine which identifier to use upon compile time

### LINKED ISSUE #131: Conditionally use either `.code()` or `.key()` as key identifier based on feature flag
Commit https://github.com/gaucho-labs/leptos-hotkeys/pull/127 reverts back to using `key()` as the keyboard identifier. However, this changes the naming conventions of keys, which is a breaking change. Therefore, we should box #127 inside a feature flag named `use_key`. 

Then we can `cfg_if` when we update our event listeners: 
https://github.com/gaucho-labs/leptos-hotkeys/blob/273df26c8d19bc655bb4d61a7995e51d9e5210ba/leptos_hotkeys/src/context.rs#L97-L105

where based on the feature flag presence, we can call `key()` or `code()`.

Finally, we'd also need to update our filtermap to account for both variations. (This doesn't need to be conditionally checked).

https://github.com/gaucho-labs/leptos-hotkeys/blob/main/leptos_hotkeys/src/hotkey.rs#L48-L72

Linking: https://github.com/gaucho-labs/leptos-hotkeys/issues/121

### PR DESCRIPTION
**Pull request by friendlymatthew**
closes #131 

ccing @maxbergmark @rkimoakbioinformatics

### CODE REVIEW

**Comment by maxbergmark** [comment]
Looks good! I think I'll have to make a slight modification to my branch to handle spacebar the same way.

**Comment by friendlymatthew** [comment]
> Looks good! I think I'll have to make a slight modification to my branch to handle spacebar the same way.

Once we get #120 merged in, we can update this branch and you can reapply that change in this PR.

**Comment by friendlymatthew** [comment]
> Looks good! I think I'll have to make a slight modification to my branch to handle spacebar the same way.



> > Looks good! I think I'll have to make a slight modification to my branch to handle spacebar the same way.
> 
> Once we get #120 merged in, we can update this branch and you can reapply that change in this PR.

Hmm thinking about this more, I think the order of merging PRs should be this one first, then #120. Should make things easier that way

**Comment by maxbergmark** [comment]
@friendlymatthew I added the feature flag fix here too, should be good to go but feel free to review!

**Comment by friendlymatthew** [comment]
> @friendlymatthew I added the feature flag fix here too, should be good to go but feel free to review!

Thanks @maxbergmark!

**Pull request merged**
